#include<bits/extc++.h>
using namespace std;
int main(int argc, char** argv) {
    string OLD = R"d( code here)d";
    string NEW = R"d( code)d";
    string content = R"d(- Enable file name extension view in file explorer.

- Read the problem statement from "_000_Task.txt".
    - Find the input/output formats and their examples.
    - Find the scoring distribution and constraints and time limit and hints.
- Find the forbidden keywords from "_000_Forbidden.txt".

- Write your code in "Solution.cpp" or "Solution.java" or "Solution.py".
    - Do not use any of the forbidden keywords in your code.
    - Do not use any external library (such as numpy) in your code.
    - Write your code in a way such that it takes input only from stdin and
        gives output only to stdout.
    - Write your code in a way such that it exits with a return code of 0 after
        all operations are finished.
- Do not edit any of the other given files.

- Run "_000_Checker.bat" to check the tentative score of your solution.
    - One of the ways to run this file is from a terminal using the command
        ".\_000_Checker.bat" (after changing to the correct directory).
    - After running this file a tentative score is given in a range of 0 to 1
        and some files are generated.
    - A copy of the stdin forwarded to your code in the X'th batch is flushed
        into "inpX.txt".
    - A copy of the stdout generated by your code in the X'th batch is flushed
        into "outX.txt".
    - "_000_00000000.cpp" or "_000_00000000.java" or "_000_00000000.py"
        is updated automatically with your best scoring solution.
    - You can read any of the generated files aiming to improve your solution
        but do not try to edit them.
- Do not delete any of the given files.)d";
    OLD = "_000_"; NEW = string(argv[2]).substr(0, 5);
    // getline(ifstream(argv[1]), content, '\0');
    for (size_t i = 0; (i = content.find(OLD, i)) != string::npos;)
        content.replace(i, OLD.size(), NEW), i += NEW.size();
    (ofstream(argv[1]) << content).close();
    exit(0);
}